import os

AUDIT_DIR = r"C:\Users\krish\FYP\audit"
REPORT_TXT = os.path.join(AUDIT_DIR, "fsfast_command_verification.txt")

def main():
    report_content = """=== FS-FAST COMMAND & NIPYPE INTERFACE VERIFICATION ===

--- 1. mri_robust_register / nipype.interfaces.freesurfer.RobustRegister ---
1. Command/Interface Exists: YES.
2. Exact command-line: `mri_robust_register --mov <source> --dst <target> --lta <output.lta> --satit --iscale`
3. Accepts 4D BOLD data: NO. `mri_robust_register` strictly operates on 3D volumes. 
4. Performs intended operation: Partially. It performs highly robust rigid-body registration, but it does NOT perform 4D time-series motion correction natively.
5. Expected input/output: 3D NIfTI -> 3D NIfTI + LTA affine transform matrix.
6. Dependencies: Requires FreeSurfer. Does not require T1w or FSL.
**ISSUE DETECTED**: Because it only accepts 3D data, using it for 4D BOLD motion correction would require splitting the 4D file into hundreds of 3D files, registering each individually to a reference volume, and concatenating them back together. This is highly inefficient and not how standard fMRI motion correction is performed. 

--- 2. mri_vol2vol / nipype.interfaces.freesurfer.ApplyVolTransform ---
1. Command/Interface Exists: YES.
2. Exact command-line: `mri_vol2vol --mov <mov.nii> --targ <ref.nii> --lta <transform.lta> --o <out.nii>`
3. Accepts 4D BOLD data: YES, it can apply a single transform to all frames, or accept an LTA for each frame if invoked in a loop.
4. Performs intended operation: Applies the registration transform generated by mri_robust_register.
5. Expected input/output: NIfTI + LTA -> NIfTI.
6. Dependencies: Requires FreeSurfer. Does not require T1w or FSL.
**ISSUE DETECTED**: Same as above; applying motion correction to a 4D file requires 139 individual LTA transforms for a 140-volume acquisition, requiring a massive loop/MapNode.

--- 3. mri_fwhm / mri_smooth / nipype.interfaces.freesurfer.Smooth ---
1. Command/Interface Exists: YES.
2. Exact command-line: `mri_fwhm --i <in.nii> --fwhm <size> --o <out.nii>` (mri_smooth is surface-only).
3. Accepts 4D BOLD data: YES. `mri_fwhm` natively supports 4D volumetric smoothing.
4. Performs intended operation: YES, performs Gaussian spatial smoothing in native functional volume space.
5. Expected input/output: 4D NIfTI -> 4D NIfTI.
6. Dependencies: Requires FreeSurfer. Does not require T1w or FSL.

--- 4. mri_glmfit / nipype.interfaces.freesurfer.GLMFit ---
1. Command/Interface Exists: YES.
2. Exact command-line: `mri_glmfit --y <bold.nii> --glmdir <outdir> --X <design.mat>`
3. Accepts 4D BOLD data: YES.
4. Performs intended operation: YES, it fits a General Linear Model to every voxel across time. It can regress out polynomials (for high/low pass filtering) and motion parameters.
5. Expected input/output: 4D NIfTI + Design Matrix -> Parameter Estimates / Residual 4D NIfTI.
6. Dependencies: Requires FreeSurfer. Does not require T1w or FSL.
**WARNING**: `mri_glmfit` requires a manually constructed design matrix file (`.mat` or `.fsgd`) containing the motion parameters and polynomial regressors. Nipype does not automatically build this matrix; it requires a custom Python node to generate the FreeSurfer-compatible matrix file from the motion correction outputs.

--- 5. nipype.interfaces.freesurfer.MRIConvert ---
1. Command/Interface Exists: YES.
2. Exact command-line: `mri_convert <in.nii> <out.nii>`
3. Accepts 4D BOLD data: YES.
4. Performs intended operation: Format conversion, reshaping, and resampling.
5. Expected input/output: NIfTI -> NIfTI.
6. Dependencies: Requires FreeSurfer. Does not require T1w or FSL.

=== SEQUENCE VERIFICATION ===
Intended Sequence: BOLD -> MoCo -> Smooth -> TempFilter/Nuisance -> Preprocessed BOLD -> ROI -> Matrix
Result: FAILED / UNSUITABLE

Reasoning for Failure:
1. 4D Motion Correction: FreeSurfer's `mri_robust_register` is purely 3D. While it is theoretically possible to split a 4D file into 140 individual 3D NIfTI files, register each one, and merge them back using a custom Python script or Nipype MapNode, this is highly fragile, slow, and non-standard. FS-FAST avoids this by shipping with a customized AFNI binary (`mc-afni2` / `3dvolreg`) specifically to handle 4D motion correction. Since you forbade ANTs and AFNI (as well as FSL), and we cannot use the overarching `preproc-sess` script without a T1w image, we lack a direct, native, 4D-capable FreeSurfer binary for motion correction.
2. Nuisance Matrix Generation: `mri_glmfit` is perfectly capable of temporal filtering and nuisance regression, but the design matrix must be manually coded to FreeSurfer specifications.

=== CONCLUSION ===
The proposed architecture (using `mri_robust_register` for MoCo) is computationally unfeasible for 4D BOLD data in Nipype without either:
A) Introducing AFNI (`3dvolreg` / `mc-afni2`), which FS-FAST actually uses under the hood.
B) Introducing FSL (`mcflirt`), which you strictly forbade.
C) Writing a massive custom Python script to split the 4D image, run 140 separate 3D registrations, and merge them, which is computationally expensive and prone to interpolation artifacts.

STOPPING as instructed. I am reporting that `mri_robust_register` is UNSUITABLE for 4D BOLD motion correction without a splitting wrapper, and FS-FAST natively relies on an AFNI wrapper (`mc-afni2`) for this exact reason. Waiting for your approval on how to proceed.
"""
    os.makedirs(AUDIT_DIR, exist_ok=True)
    with open(REPORT_TXT, "w", encoding="utf-8") as f:
        f.write(report_content)

    print(f"Command verification report successfully generated at: {REPORT_TXT}")

if __name__ == "__main__":
    main()
